language: csharp
#solution: MathParser/MathParser.sln

install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console

script:
  - xbuild ./MathParser/MathParser.sln
  - nunit-console ./MathParser/UnitTest/bin/UnitTest.dll
